project_id = "jjuqvqynftbfdjyawtzm"

[functions.parse-voice-input]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.generate-logo]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true
