import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "ru" | "es";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Landing page
    "landing.badge": "Better Communication, Stronger Connection",
    "landing.hero.title": "Clear the Air in Your",
    "landing.hero.title.highlight": "Relationship",
    "landing.hero.description": "In many relationships, especially when it comes to intimacy and expectations, misunderstandings create distance. Spark Meter helps couples communicate honestly about their needs, desires, and emotional state.",
    "landing.cta.primary": "Get Started Free",
    "landing.cta.secondary": "Learn More",
    "landing.cta.login": "Login",
    "landing.features.title": "How It Works",
    "landing.features.subtitle": "Simple daily check-ins that strengthen your bond",
    "landing.feature1.title": "Connect as Partners",
    "landing.feature1.description": "Create your account and connect through a private invitation link.",
    "landing.feature2.title": "Daily Check-ins",
    "landing.feature2.description": "Share your intimacy level, mood, sleep quality, and emotions with simple sliders or voice input.",
    "landing.feature3.title": "Track & Grow Together",
    "landing.feature3.description": "View trends, celebrate wins, and understand each other better over time.",
    "landing.benefits.badge": "Why Choose Spark Meter",
    "landing.benefits.title": "Why Couples Love Spark Meter",
    "landing.benefits.subtitle": "Real transparency leads to real intimacy",
    "landing.benefit1.title": "Private & Safe",
    "landing.benefit1.description": "Your data is completely private. Even admins can't see your personal entries.",
    "landing.benefit2.title": "Reduces Misunderstandings",
    "landing.benefit2.description": "Clear communication about needs prevents hurt feelings and missed opportunities for intimacy.",
    "landing.benefit3.title": "Track Your Journey",
    "landing.benefit3.description": "View 30-day trends to understand patterns and strengthen your relationship over time.",
    "landing.final.title": "Start Building a More Honest Relationship Today",
    "landing.final.subtitle": "Join couples who've discovered the power of transparent communication",
    "landing.final.cta": "Create Your Account",
    "landing.pricing": "Free for 30 Days. Then $2.99/mo",
    "landing.joinForm.title": "Start Your Free Trial Today",
    "landing.joinForm.subtitle": "No credit card required. Join in seconds.",
    "landing.footer": "© 2025 Spark Meter. Built with love for loving couples.",
    
    // Auth page
    "auth.welcome": "Welcome Back",
    "auth.create": "Create Account",
    "auth.subtitle.login": "Sign in to continue your journey",
    "auth.subtitle.signup": "Start your journey to better communication",
    "auth.login.subtitle": "Sign in to continue your journey",
    "auth.success.login": "Welcome back!",
    "auth.displayName": "Your Name",
    "auth.displayName.placeholder": "Your name",
    "auth.role": "I am a",
    "auth.role.husband": "Husband",
    "auth.role.wife": "Wife",
    "auth.email": "Email",
    "auth.email.placeholder": "you@example.com",
    "auth.password": "Password",
    "auth.password.placeholder": "••••••••",
    "auth.button.signin": "Sign In",
    "auth.button.signup": "Create Account",
    "auth.button.loading": "Please wait...",
    "auth.switch.signup": "Don't have an account? Sign up",
    "auth.switch.login": "Already have an account? Sign in",
    "auth.toast.welcome": "Welcome back!",
    "auth.toast.redirect": "Redirecting to your dashboard...",
    "auth.toast.created": "Account created!",
    "auth.toast.welcome.new": "Welcome to Spark Meter. Setting up your profile...",
    "auth.fillAllFields": "Please fill in all fields",
    "auth.success": "Account created successfully!",
    "auth.error": "An error occurred. Please try again.",
    "auth.signingUp": "Creating account...",
    
    // Dashboard
    "dashboard.loading": "Loading...",
    "dashboard.appName": "Spark Meter",
    "dashboard.welcome": "Welcome",
    "dashboard.invite.title": "Connect with Your Partner",
    "dashboard.invite.description": "Create an invitation link to connect with your partner",
    "dashboard.invite.button": "Generate Invitation Link",
    "dashboard.invite.expires": "This link expires in 7 days. Send it to your partner to connect your accounts.",
    "dashboard.view.myLevels": "My Levels",
    "dashboard.view.partnerLevels": "See {name}'s Levels",
    "dashboard.partner.noCheckin": "{name} hasn't checked in today",
    "dashboard.partner.remind": "Remind {name}",
    "dashboard.partner.noCheckinYet": "{name} hasn't checked in today yet",
    "dashboard.remind.title": "How would you like to remind {name}?",
    "dashboard.remind.description": "Choose how to send a reminder to check in",
    "dashboard.remind.imessage": "Send iMessage",
    "dashboard.remind.email": "Send Email",
    "dashboard.remind.notification": "Send Notification",
    "dashboard.remind.success.title": "Reminder Sent!",
    "dashboard.remind.success.description": "{name} has been reminded to check in today",
    "dashboard.celebration.title": "🎉 Thank you!",
    "dashboard.celebration.description": "{name} is being notified now!",
    "dashboard.checkin.title": "Today's Check-In",
    "dashboard.checkin.intimacy": "Desire For Intimacy",
    "dashboard.checkin.feeling": "Desire For Touch",
    "dashboard.checkin.communication": "Desire For Communication",
    "dashboard.checkin.sleep": "Sleep Quality",
    "dashboard.checkin.emotional": "Emotional State",
    "dashboard.checkin.low": "Low",
    "dashboard.checkin.high": "High",
    "dashboard.checkin.bad": "Bad",
    "dashboard.checkin.great": "Great",
    "dashboard.checkin.poor": "Poor",
    "dashboard.checkin.save": "Save Check-In",
    "dashboard.checkin.voice.hint": "Tap the microphone and speak naturally about how you're feeling",
    "dashboard.trends": "View 30-Day Trends",
    "dashboard.viewLog": "View Log",
    "dashboard.toast.saved": "Saved!",
    "dashboard.toast.saved.description": "Your daily check-in has been recorded.",
    "dashboard.toast.invite.created": "Invitation created!",
    "dashboard.toast.invite.share": "Share this link with your partner",
    "dashboard.toast.copied": "Copied!",
    "dashboard.toast.copied.description": "Invitation link copied to clipboard",
    "dashboard.invite.prompt.title": "🎯 Invite Your Partner Now!",
    "dashboard.invite.prompt.description": "Getting your partner to join is crucial for Spark Meter to work. Choose the easiest way to invite them:",
    "dashboard.invite.viaiMessage": "Invite via iMessage",
    "dashboard.invite.viaEmail": "Invite via Email",
    
    // Voice input
    "voice.listening": "Listening...",
    "voice.listening.description": "Speak now to record your feelings",
    "voice.processing": "Processing...",
    "voice.saved": "Voice input saved!",
    "voice.saved.description": "Your feelings have been recorded.",
    "voice.error": "Failed to recognize speech. Please try again.",
    "voice.not.supported": "Speech recognition is not supported in your browser.",
    
    // Invite acceptance
    "invite.title": "You're Invited!",
    "invite.description": "{name} has invited you to connect on Spark Meter",
    "invite.info": "By accepting, you'll be able to share your daily feelings and see when your partner needs connection.",
    "invite.decline": "Decline",
    "invite.accept": "Accept & Connect",
    "invite.connecting": "Connecting...",
    "invite.toast.signin": "Please sign in",
    "invite.toast.signin.description": "You need to be signed in to accept an invitation",
    "invite.toast.invalid": "Invalid invitation",
    "invite.toast.invalid.description": "This invitation link is invalid or has expired",
    "invite.toast.expired": "Invitation expired",
    "invite.toast.expired.description": "This invitation link has expired",
    "invite.toast.incompatible": "Incompatible roles",
    "invite.toast.incompatible.description": "You and your partner must have different roles (husband/wife)",
    "invite.toast.connected": "Connected!",
    "invite.toast.connected.description": "You are now connected with {name}",

    // Accept Invite page
    "acceptInvite.header": "You were invited to Spark Meter by {name}",
    "acceptInvite.checkin.subtitle": "Share how you're feeling today",
    "acceptInvite.preview.title": "Preview: Your Daily Check-In",
    "acceptInvite.preview.subtitle": "This is what you'll see after signing up",
    "acceptInvite.form.title": "Create Your Account",
    "acceptInvite.form.subtitle": "You'll be automatically connected with {name}",
    "acceptInvite.button": "Create Account & Connect",
    "acceptInvite.loading": "Creating Account...",

    // Olive Branch
    "oliveBranch.title": "Extend an Olive Branch",
    "oliveBranch.description": "Send a heartfelt message to {name}. Record your voice or type a message.",
    "oliveBranch.record": "Record Voice Message",
    "oliveBranch.stopRecording": "Stop Recording",
    "oliveBranch.yourMessage": "Your Message",
    "oliveBranch.placeholder": "Type or record a message for {name}...",
    "oliveBranch.send": "Send Olive Branch",
    "oliveBranch.sending": "Sending...",
    "oliveBranch.transcribing": "Transcribing your message...",
    "oliveBranch.toast.sent": "Message sent!",
    "oliveBranch.toast.sentDesc": "Your Olive Branch has been extended to {name}",
    "oliveBranch.toast.empty": "Empty message",
    "oliveBranch.toast.emptyDesc": "Please record or type a message first",
    "oliveBranch.toast.error": "Error",
    "oliveBranch.toast.errorDesc": "Failed to send message. Please try again.",
    "oliveBranch.toast.recordStart": "Recording started",
    "oliveBranch.toast.recordStartDesc": "Speak your message for your partner",
    "oliveBranch.toast.recordError": "Failed to start recording. Please check microphone permissions.",
    "oliveBranch.toast.transcribeComplete": "Transcription complete",
    "oliveBranch.toast.transcribeCompleteDesc": "You can edit the message before sending",
    "oliveBranch.toast.transcribeError": "Failed to transcribe audio. Please try typing instead.",

    // Trial Status
    "trial.premium": "Premium",
    "trial.unlimited": "Unlimited",
    "trial.expired": "Trial Expired",
    "trial.freeTrial": "Free Trial",
    "trial.upgrade": "Upgrade $2.99/mo",
    "trial.loading": "Loading...",
    "trial.day": "day",
    "trial.days": "days",
    "trial.left": "left",

    // Quote of the Day
    "quote.title": "Quote of the Day",

    // Common
    "common.imessage": "iMessage",
    "common.email": "Email",
    "common.link": "Link",
  },
  ru: {
    // Landing page
    "landing.badge": "Лучшее общение, крепкие отношения",
    "landing.hero.title": "Откройтесь друг другу в ваших",
    "landing.hero.title.highlight": "Отношениях",
    "landing.hero.description": "Во многих отношениях, особенно когда речь идет об интимности и ожиданиях, недопонимание создает дистанцию. Spark Meter помогает парам честно общаться о своих потребностях, желаниях и эмоциональном состоянии.",
    "landing.cta.primary": "Начать бесплатно",
    "landing.cta.secondary": "Узнать больше",
    "landing.cta.login": "Войти",
    "landing.features.title": "Как это работает",
    "landing.features.subtitle": "Простые ежедневные отметки, которые укрепляют вашу связь",
    "landing.feature1.title": "Объединитесь как партнеры",
    "landing.feature1.description": "Создайте свой аккаунт и подключитесь через личную ссылку-приглашение.",
    "landing.feature2.title": "Ежедневные отметки",
    "landing.feature2.description": "Делитесь уровнем интимности, настроением, качеством сна и эмоциями с помощью простых слайдеров или голосового ввода.",
    "landing.feature3.title": "Отслеживайте и растите вместе",
    "landing.feature3.description": "Просматривайте тренды, отмечайте достижения и лучше понимайте друг друга со временем.",
    "landing.benefits.badge": "Почему выбирают Spark Meter",
    "landing.benefits.title": "Почему пары любят Spark Meter",
    "landing.benefits.subtitle": "Настоящая прозрачность ведет к настоящей близости",
    "landing.benefit1.title": "Приватно и безопасно",
    "landing.benefit1.description": "Ваши данные полностью конфиденциальны. Даже администраторы не могут видеть ваши личные записи.",
    "landing.benefit2.title": "Уменьшает недопонимание",
    "landing.benefit2.description": "Четкое общение о потребностях предотвращает обиды и упущенные возможности для близости.",
    "landing.benefit3.title": "Следите за своим путем",
    "landing.benefit3.description": "Просматривайте 30-дневные тренды, чтобы понимать паттерны и укреплять отношения со временем.",
    "landing.final.title": "Начните строить более честные отношения сегодня",
    "landing.final.subtitle": "Присоединяйтесь к парам, которые открыли силу прозрачного общения",
    "landing.final.cta": "Создать аккаунт",
    "landing.pricing": "Бесплатно 30 дней. Затем $2.99/мес",
    "landing.joinForm.title": "Начните бесплатный пробный период сегодня",
    "landing.joinForm.subtitle": "Кредитная карта не требуется. Присоединяйтесь за секунды.",
    "landing.footer": "© 2025 Spark Meter. Создано с любовью для любящих пар.",
    
    // Auth page
    "auth.welcome": "С возвращением",
    "auth.create": "Создать аккаунт",
    "auth.subtitle.login": "Войдите, чтобы продолжить свой путь",
    "auth.subtitle.signup": "Начните свой путь к лучшему общению",
    "auth.login.subtitle": "Войдите, чтобы продолжить свой путь",
    "auth.success.login": "С возвращением!",
    "auth.displayName": "Ваше имя",
    "auth.displayName.placeholder": "Ваше имя",
    "auth.role": "Я",
    "auth.role.husband": "Муж",
    "auth.role.wife": "Жена",
    "auth.email": "Электронная почта",
    "auth.email.placeholder": "you@example.com",
    "auth.password": "Пароль",
    "auth.password.placeholder": "••••••••",
    "auth.button.signin": "Войти",
    "auth.button.signup": "Создать аккаунт",
    "auth.button.loading": "Пожалуйста, подождите...",
    "auth.switch.signup": "Нет аккаунта? Зарегистрируйтесь",
    "auth.switch.login": "Уже есть аккаунт? Войти",
    "auth.toast.welcome": "С возвращением!",
    "auth.toast.redirect": "Перенаправление на панель управления...",
    "auth.toast.created": "Аккаунт создан!",
    "auth.toast.welcome.new": "Добро пожаловать в Spark Meter. Настраиваем ваш профиль...",
    "auth.fillAllFields": "Пожалуйста, заполните все поля",
    "auth.success": "Аккаунт успешно создан!",
    "auth.error": "Произошла ошибка. Пожалуйста, попробуйте снова.",
    "auth.signingUp": "Создание аккаунта...",
    
    // Dashboard
    "dashboard.loading": "Загрузка...",
    "dashboard.appName": "Spark Meter",
    "dashboard.welcome": "Добро пожаловать",
    "dashboard.invite.title": "Подключите партнера",
    "dashboard.invite.description": "Создайте ссылку-приглашение для подключения партнера",
    "dashboard.invite.button": "Создать ссылку-приглашение",
    "dashboard.invite.expires": "Ссылка действительна 7 дней. Отправьте ее партнеру для подключения.",
    "dashboard.view.myLevels": "Мои уровни",
    "dashboard.view.partnerLevels": "Уровни {name}",
    "dashboard.partner.noCheckin": "{name} еще не отмечался(лась) сегодня",
    "dashboard.partner.remind": "Напомнить {name}",
    "dashboard.partner.noCheckinYet": "{name} еще не отмечался(лась) сегодня",
    "dashboard.remind.title": "Как вы хотите напомнить {name}?",
    "dashboard.remind.description": "Выберите способ отправки напоминания",
    "dashboard.remind.imessage": "Отправить iMessage",
    "dashboard.remind.email": "Отправить Email",
    "dashboard.remind.notification": "Отправить уведомление",
    "dashboard.remind.success.title": "Напоминание отправлено!",
    "dashboard.remind.success.description": "{name} получил(а) напоминание о регистрации сегодня",
    "dashboard.celebration.title": "🎉 Спасибо!",
    "dashboard.celebration.description": "{name} получает уведомление!",
    "dashboard.checkin.title": "Сегодняшняя отметка",
    "dashboard.checkin.intimacy": "Желание интимности",
    "dashboard.checkin.feeling": "Желание прикосновений",
    "dashboard.checkin.communication": "Желание общения",
    "dashboard.checkin.sleep": "Качество сна",
    "dashboard.checkin.emotional": "Эмоциональное состояние",
    "dashboard.checkin.low": "Низко",
    "dashboard.checkin.high": "Высоко",
    "dashboard.checkin.bad": "Плохо",
    "dashboard.checkin.great": "Отлично",
    "dashboard.checkin.poor": "Плохое",
    "dashboard.checkin.save": "Сохранить отметку",
    "dashboard.checkin.voice.hint": "Нажмите на микрофон и расскажите естественно о своих ощущениях",
    "dashboard.trends": "Просмотр трендов за 30 дней",
    "dashboard.viewLog": "Просмотр журнала",
    "dashboard.toast.saved": "Сохранено!",
    "dashboard.toast.saved.description": "Ваша ежедневная отметка записана.",
    "dashboard.toast.invite.created": "Приглашение создано!",
    "dashboard.toast.invite.share": "Поделитесь этой ссылкой с партнером",
    "dashboard.toast.copied": "Скопировано!",
    "dashboard.toast.copied.description": "Ссылка-приглашение скопирована в буфер обмена",
    "dashboard.invite.prompt.title": "🎯 Пригласите партнера сейчас!",
    "dashboard.invite.prompt.description": "Присоединение вашего партнера критически важно для работы Spark Meter. Выберите самый простой способ пригласить его:",
    "dashboard.invite.viaiMessage": "Пригласить через iMessage",
    "dashboard.invite.viaEmail": "Пригласить через Email",
    
    // Voice input
    "voice.listening": "Слушаю...",
    "voice.listening.description": "Говорите сейчас, чтобы записать свои ощущения",
    "voice.processing": "Обработка...",
    "voice.saved": "Голосовой ввод сохранен!",
    "voice.saved.description": "Ваши ощущения записаны.",
    "voice.error": "Не удалось распознать речь. Попробуйте еще раз.",
    "voice.not.supported": "Распознавание речи не поддерживается в вашем браузере.",
    
    // Invite acceptance
    "invite.title": "Вас пригласили!",
    "invite.description": "{name} пригласил(а) вас подключиться к Spark Meter",
    "invite.info": "Приняв приглашение, вы сможете делиться своими ежедневными чувствами и видеть, когда вашему партнеру нужна связь.",
    "invite.decline": "Отклонить",
    "invite.accept": "Принять и подключиться",
    "invite.connecting": "Подключение...",
    "invite.toast.signin": "Пожалуйста, войдите",
    "invite.toast.signin.description": "Вам нужно войти, чтобы принять приглашение",
    "invite.toast.invalid": "Неверное приглашение",
    "invite.toast.invalid.description": "Эта ссылка-приглашение недействительна или истекла",
    "invite.toast.expired": "Приглашение истекло",
    "invite.toast.expired.description": "Срок действия этой ссылки истек",
    "invite.toast.incompatible": "Несовместимые роли",
    "invite.toast.incompatible.description": "У вас и вашего партнера должны быть разные роли (муж/жена)",
    "invite.toast.connected": "Подключено!",
    "invite.toast.connected.description": "Вы теперь подключены с {name}",

    // Accept Invite page
    "acceptInvite.header": "Вас пригласил(а) в Spark Meter {name}",
    "acceptInvite.checkin.subtitle": "Поделитесь своими ощущениями сегодня",
    "acceptInvite.preview.title": "Предпросмотр: Ежедневная отметка",
    "acceptInvite.preview.subtitle": "Так будет выглядеть экран после регистрации",
    "acceptInvite.form.title": "Создайте аккаунт",
    "acceptInvite.form.subtitle": "Вы автоматически подключитесь с {name}",
    "acceptInvite.button": "Создать аккаунт и подключиться",
    "acceptInvite.loading": "Создание аккаунта...",

    // Olive Branch
    "oliveBranch.title": "Протянуть оливковую ветвь",
    "oliveBranch.description": "Отправьте искреннее сообщение {name}. Запишите голос или напишите.",
    "oliveBranch.record": "Записать голосовое сообщение",
    "oliveBranch.stopRecording": "Остановить запись",
    "oliveBranch.yourMessage": "Ваше сообщение",
    "oliveBranch.placeholder": "Напишите или запишите сообщение для {name}...",
    "oliveBranch.send": "Отправить оливковую ветвь",
    "oliveBranch.sending": "Отправка...",
    "oliveBranch.transcribing": "Расшифровка вашего сообщения...",
    "oliveBranch.toast.sent": "Сообщение отправлено!",
    "oliveBranch.toast.sentDesc": "Ваша оливковая ветвь протянута к {name}",
    "oliveBranch.toast.empty": "Пустое сообщение",
    "oliveBranch.toast.emptyDesc": "Пожалуйста, сначала запишите или напишите сообщение",
    "oliveBranch.toast.error": "Ошибка",
    "oliveBranch.toast.errorDesc": "Не удалось отправить сообщение. Попробуйте еще раз.",
    "oliveBranch.toast.recordStart": "Запись начата",
    "oliveBranch.toast.recordStartDesc": "Говорите ваше сообщение для партнера",
    "oliveBranch.toast.recordError": "Не удалось начать запись. Проверьте разрешения микрофона.",
    "oliveBranch.toast.transcribeComplete": "Расшифровка завершена",
    "oliveBranch.toast.transcribeCompleteDesc": "Вы можете отредактировать сообщение перед отправкой",
    "oliveBranch.toast.transcribeError": "Не удалось расшифровать аудио. Попробуйте напечатать.",

    // Trial Status
    "trial.premium": "Премиум",
    "trial.unlimited": "Неограниченно",
    "trial.expired": "Пробный период истек",
    "trial.freeTrial": "Бесплатная пробная версия",
    "trial.upgrade": "Обновить $2.99/мес",
    "trial.loading": "Загрузка...",
    "trial.day": "день",
    "trial.days": "дней",
    "trial.left": "осталось",

    // Quote of the Day
    "quote.title": "Цитата дня",

    // Common
    "common.imessage": "iMessage",
    "common.email": "Email",
    "common.link": "Ссылка",
  },
  es: {
    // Landing page
    "landing.badge": "Mejor comunicación, conexión más fuerte",
    "landing.hero.title": "Aclara las cosas en tu",
    "landing.hero.title.highlight": "Relación",
    "landing.hero.description": "En muchas relaciones, especialmente cuando se trata de intimidad y expectativas, los malentendidos crean distancia. Spark Meter ayuda a las parejas a comunicarse honestamente sobre sus necesidades, deseos y estado emocional.",
    "landing.cta.primary": "Comienza Gratis",
    "landing.cta.secondary": "Más Información",
    "landing.cta.login": "Iniciar Sesión",
    "landing.features.title": "Cómo Funciona",
    "landing.features.subtitle": "Chequeos diarios simples que fortalecen tu vínculo",
    "landing.feature1.title": "Conecta como Pareja",
    "landing.feature1.description": "Crea tu cuenta y conéctate a través de un enlace de invitación privado.",
    "landing.feature2.title": "Chequeos Diarios",
    "landing.feature2.description": "Comparte tu nivel de intimidad, estado de ánimo, calidad del sueño y emociones con deslizadores simples o entrada de voz.",
    "landing.feature3.title": "Sigue y Crece Juntos",
    "landing.feature3.description": "Ve tendencias, celebra victorias y entiéndanse mejor con el tiempo.",
    "landing.benefits.badge": "Por Qué Elegir Spark Meter",
    "landing.benefits.title": "Por Qué las Parejas Aman Spark Meter",
    "landing.benefits.subtitle": "La transparencia real lleva a la intimidad real",
    "landing.benefit1.title": "Privado y Seguro",
    "landing.benefit1.description": "Tus datos son completamente privados. Ni siquiera los administradores pueden ver tus entradas personales.",
    "landing.benefit2.title": "Reduce Malentendidos",
    "landing.benefit2.description": "La comunicación clara sobre las necesidades previene sentimientos heridos y oportunidades perdidas de intimidad.",
    "landing.benefit3.title": "Sigue Tu Camino",
    "landing.benefit3.description": "Ve tendencias de 30 días para entender patrones y fortalecer tu relación con el tiempo.",
    "landing.final.title": "Comienza a Construir una Relación Más Honesta Hoy",
    "landing.final.subtitle": "Únete a parejas que han descubierto el poder de la comunicación transparente",
    "landing.final.cta": "Crea Tu Cuenta",
    "landing.pricing": "Gratis por 30 días. Luego $2.99/mes",
    "landing.joinForm.title": "Comienza Tu Prueba Gratuita Hoy",
    "landing.joinForm.subtitle": "No se requiere tarjeta de crédito. Únete en segundos.",
    "landing.footer": "© 2025 Spark Meter. Construido con amor para parejas amorosas.",
    
    // Auth page
    "auth.welcome": "Bienvenido de Nuevo",
    "auth.create": "Crear Cuenta",
    "auth.subtitle.login": "Inicia sesión para continuar tu viaje",
    "auth.subtitle.signup": "Comienza tu viaje hacia una mejor comunicación",
    "auth.login.subtitle": "Inicia sesión para continuar tu viaje",
    "auth.success.login": "¡Bienvenido de nuevo!",
    "auth.displayName": "Tu Nombre",
    "auth.displayName.placeholder": "Tu nombre",
    "auth.role": "Soy",
    "auth.role.husband": "Esposo",
    "auth.role.wife": "Esposa",
    "auth.email": "Correo Electrónico",
    "auth.email.placeholder": "tu@ejemplo.com",
    "auth.password": "Contraseña",
    "auth.password.placeholder": "••••••••",
    "auth.button.signin": "Iniciar Sesión",
    "auth.button.signup": "Crear Cuenta",
    "auth.button.loading": "Por favor espera...",
    "auth.switch.signup": "¿No tienes cuenta? Regístrate",
    "auth.switch.login": "¿Ya tienes cuenta? Inicia sesión",
    "auth.toast.welcome": "¡Bienvenido de nuevo!",
    "auth.toast.redirect": "Redirigiendo a tu panel...",
    "auth.toast.created": "¡Cuenta creada!",
    "auth.toast.welcome.new": "Bienvenido a Spark Meter. Configurando tu perfil...",
    "auth.fillAllFields": "Por favor, complete todos los campos",
    "auth.success": "¡Cuenta creada exitosamente!",
    "auth.error": "Ocurrió un error. Por favor, intenta de nuevo.",
    "auth.signingUp": "Creando cuenta...",
    
    // Dashboard
    "dashboard.loading": "Cargando...",
    "dashboard.appName": "Spark Meter",
    "dashboard.welcome": "Bienvenido",
    "dashboard.invite.title": "Conecta con Tu Pareja",
    "dashboard.invite.description": "Crea un enlace de invitación para conectar con tu pareja",
    "dashboard.invite.button": "Generar Enlace de Invitación",
    "dashboard.invite.expires": "Este enlace expira en 7 días. Envíalo a tu pareja para conectar sus cuentas.",
    "dashboard.view.myLevels": "Mis Niveles",
    "dashboard.view.partnerLevels": "Ver Niveles de {name}",
    "dashboard.partner.noCheckin": "{name} no se ha registrado hoy",
    "dashboard.partner.remind": "Recordar a {name}",
    "dashboard.partner.noCheckinYet": "{name} aún no se ha registrado hoy",
    "dashboard.remind.title": "¿Cómo te gustaría recordarle a {name}?",
    "dashboard.remind.description": "Elige cómo enviar un recordatorio para registrarse",
    "dashboard.remind.imessage": "Enviar iMessage",
    "dashboard.remind.email": "Enviar Email",
    "dashboard.remind.notification": "Enviar Notificación",
    "dashboard.remind.success.title": "¡Recordatorio Enviado!",
    "dashboard.remind.success.description": "{name} ha sido recordado(a) para registrarse hoy",
    "dashboard.celebration.title": "🎉 ¡Gracias!",
    "dashboard.celebration.description": "¡{name} está siendo notificado ahora!",
    "dashboard.checkin.title": "Chequeo de Hoy",
    "dashboard.checkin.intimacy": "Deseo de Intimidad",
    "dashboard.checkin.feeling": "Deseo de Contacto",
    "dashboard.checkin.communication": "Deseo de Comunicación",
    "dashboard.checkin.sleep": "Calidad del Sueño",
    "dashboard.checkin.emotional": "Estado Emocional",
    "dashboard.checkin.low": "Bajo",
    "dashboard.checkin.high": "Alto",
    "dashboard.checkin.bad": "Malo",
    "dashboard.checkin.great": "Excelente",
    "dashboard.checkin.poor": "Pobre",
    "dashboard.checkin.save": "Guardar Chequeo",
    "dashboard.checkin.voice.hint": "Toca el micrófono y habla naturalmente sobre cómo te sientes",
    "dashboard.trends": "Ver Tendencias de 30 Días",
    "dashboard.viewLog": "Ver Registro",
    "dashboard.toast.saved": "¡Guardado!",
    "dashboard.toast.saved.description": "Tu chequeo diario ha sido registrado.",
    "dashboard.toast.invite.created": "¡Invitación creada!",
    "dashboard.toast.invite.share": "Comparte este enlace con tu pareja",
    "dashboard.toast.copied": "¡Copiado!",
    "dashboard.toast.copied.description": "Enlace de invitación copiado al portapapeles",
    "dashboard.invite.prompt.title": "🎯 ¡Invita a Tu Pareja Ahora!",
    "dashboard.invite.prompt.description": "Que tu pareja se una es crucial para que Spark Meter funcione. Elige la manera más fácil de invitarle:",
    "dashboard.invite.viaiMessage": "Invitar por iMessage",
    "dashboard.invite.viaEmail": "Invitar por Email",
    
    // Voice input
    "voice.listening": "Escuchando...",
    "voice.listening.description": "Habla ahora para grabar tus sentimientos",
    "voice.processing": "Procesando...",
    "voice.saved": "¡Entrada de voz guardada!",
    "voice.saved.description": "Tus sentimientos han sido registrados.",
    "voice.error": "No se pudo reconocer el habla. Inténtalo de nuevo.",
    "voice.not.supported": "El reconocimiento de voz no es compatible con tu navegador.",
    
    // Invite acceptance
    "invite.title": "¡Estás Invitado!",
    "invite.description": "{name} te ha invitado a conectarte en Spark Meter",
    "invite.info": "Al aceptar, podrás compartir tus sentimientos diarios y ver cuándo tu pareja necesita conexión.",
    "invite.decline": "Rechazar",
    "invite.accept": "Aceptar y Conectar",
    "invite.connecting": "Conectando...",
    "invite.toast.signin": "Por favor inicia sesión",
    "invite.toast.signin.description": "Debes iniciar sesión para aceptar una invitación",
    "invite.toast.invalid": "Invitación inválida",
    "invite.toast.invalid.description": "Este enlace de invitación es inválido o ha expirado",
    "invite.toast.expired": "Invitación expirada",
    "invite.toast.expired.description": "Este enlace de invitación ha expirado",
    "invite.toast.incompatible": "Roles incompatibles",
    "invite.toast.incompatible.description": "Tú y tu pareja deben tener roles diferentes (esposo/esposa)",
    "invite.toast.connected": "¡Conectado!",
    "invite.toast.connected.description": "Ahora estás conectado con {name}",

    // Accept Invite page
    "acceptInvite.header": "Fuiste invitado a Spark Meter por {name}",
    "acceptInvite.checkin.subtitle": "Comparte cómo te sientes hoy",
    "acceptInvite.preview.title": "Vista Previa: Tu Chequeo Diario",
    "acceptInvite.preview.subtitle": "Esto es lo que verás después de registrarte",
    "acceptInvite.form.title": "Crea Tu Cuenta",
    "acceptInvite.form.subtitle": "Te conectarás automáticamente con {name}",
    "acceptInvite.button": "Crear Cuenta y Conectar",
    "acceptInvite.loading": "Creando Cuenta...",

    // Olive Branch
    "oliveBranch.title": "Extender una Rama de Olivo",
    "oliveBranch.description": "Envía un mensaje sincero a {name}. Graba tu voz o escribe un mensaje.",
    "oliveBranch.record": "Grabar Mensaje de Voz",
    "oliveBranch.stopRecording": "Detener Grabación",
    "oliveBranch.yourMessage": "Tu Mensaje",
    "oliveBranch.placeholder": "Escribe o graba un mensaje para {name}...",
    "oliveBranch.send": "Enviar Rama de Olivo",
    "oliveBranch.sending": "Enviando...",
    "oliveBranch.transcribing": "Transcribiendo tu mensaje...",
    "oliveBranch.toast.sent": "¡Mensaje enviado!",
    "oliveBranch.toast.sentDesc": "Tu Rama de Olivo ha sido extendida a {name}",
    "oliveBranch.toast.empty": "Mensaje vacío",
    "oliveBranch.toast.emptyDesc": "Por favor graba o escribe un mensaje primero",
    "oliveBranch.toast.error": "Error",
    "oliveBranch.toast.errorDesc": "No se pudo enviar el mensaje. Inténtalo de nuevo.",
    "oliveBranch.toast.recordStart": "Grabación iniciada",
    "oliveBranch.toast.recordStartDesc": "Habla tu mensaje para tu pareja",
    "oliveBranch.toast.recordError": "No se pudo iniciar la grabación. Verifica los permisos del micrófono.",
    "oliveBranch.toast.transcribeComplete": "Transcripción completa",
    "oliveBranch.toast.transcribeCompleteDesc": "Puedes editar el mensaje antes de enviarlo",
    "oliveBranch.toast.transcribeError": "No se pudo transcribir el audio. Intenta escribir en su lugar.",

    // Trial Status
    "trial.premium": "Premium",
    "trial.unlimited": "Ilimitado",
    "trial.expired": "Prueba Expirada",
    "trial.freeTrial": "Prueba Gratuita",
    "trial.upgrade": "Actualizar $2.99/mes",
    "trial.loading": "Cargando...",
    "trial.day": "día",
    "trial.days": "días",
    "trial.left": "restante",

    // Quote of the Day
    "quote.title": "Cita del Día",

    // Common
    "common.imessage": "iMessage",
    "common.email": "Email",
    "common.link": "Enlace",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("en");

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
